//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Mg.Framework;
namespace RepositoryModel
{
    /// <summary>
    /// 实体类Customer。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("Customer")]
    [Serializable]
    public partial class Customer:BaseModel
    {
       #region Model 
		/// <summary>
		/// 
		/// </summary>
		public int RowNo{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsStop{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Mender{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ModifyDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Code{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Name{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string AbbrName{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string MnemonicCode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SaleArea{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? Area{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CustomerCategoryID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Industry{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Grade{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string PrimaryContact{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ContactPhone{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SalesMan{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Merchandiser{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Text{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Fax{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Address{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string PostCode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Email{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string DeliveryAddress{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string OfficialWeb{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Currency{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ReceiptType{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? TaxRate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string CashAsset{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? DepositRate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BankAccount{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BankName{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string CreditRating{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? IFLineCredit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? IFCreditLimit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? LineCredit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreditLimit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BusinessLicense{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BusinessCertificate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string LegalPerson{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BusinessScope{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? RegisteredCapital{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string TAXID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string EnglishName{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CountryID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Brand{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string EnglishAddress{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string RegistrationCode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BondedSupervisionType{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Destination{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string MajorCarriers{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string TransportNode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? CommissionRate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PremiumRate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public long AutoID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? DepartmentID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BillType{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string NamePYCode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string CloseUser{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CloseDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string LargeRegions{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SubRegions{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Source{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string AttrInfo{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string LatentDemand{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BuyGoods{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Product{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SurplusLimit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string InCompanyName{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? ProvinceID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CityID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CountyID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public int? TimeLimitDay{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Audit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AuditDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? FirstCheckDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Remark{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string RegionalManager{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Maker{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? MakeDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? StopDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string StopOper{get;set;}
		#endregion

}
}