//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Mg.Framework;
namespace RepositoryModel
{
    /// <summary>
    /// 实体类SalesOrder。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("SalesOrder")]
    [Serializable]
    public partial class SalesOrder :BaseModel
    {
        [Column(IsPrimaryKey =true,Name ="ID")]
        public override Guid Id { get; set; }
        #region Model 
        /// <summary>
        /// 
        /// </summary>
        public int RowNo{get;set;}
		/// <summary>
		/// 
		/// </summary>
        [AutoIncrement]
		public long AutoID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BillCode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Maker{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? MakeDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Audit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? FirstAuditDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AuditDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public int? States{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Mender{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ModifyDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ManualNumber{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? OrderDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Salesman{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Merchandiser{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CustomerID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string DeliveryMethod{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AcceptDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ContractNo{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? PackingID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Project{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string OrderType{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? DepartmentID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Subscription{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Specialpricing{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Remark{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string CustomerPO{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string DeliveryAddress{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BillType{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? AluminumPriceDateID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? FinishDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string FinishOper{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ProductionEndDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ProductionEndOper{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? AluminumPrice{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Approval{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ApprovalDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string CloseUser{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CloseDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? TruckID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AluminumPriceDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string LargeRegions{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SubRegions{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? TotalAmount{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string DepositRatio2{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string DepositRatio1{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? DepositAmount1{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? DepositAmount2{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsRefuse{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string RefuseReason{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string freight{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string freight1{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string AluminumPriceValuation{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string OpenMode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string GlassThickness{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string OnlineAudited{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? WithoutApproval{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ConfirmOperator{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ConfirmedDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsOrderSuspend{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsOrderCancel{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? WithTax{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string OrderCategory{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? BelongsCustomer{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Sign{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? DepositFlag{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? DepositWeight{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? DepositPrice{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? DepositAmount{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string PreAudit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? PreAuditDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? PlanFinishDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public int? LimitedProductionQuantity{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ExtrusionEndDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ExtrusionEndOper{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string CustomerBillCode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string AddAudit{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? AddAuditDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string belongcompany{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Currency{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public int? PrintCount{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Memo{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Telephonist{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? SalesManWareHouseAreaID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? CalculatedAluminumPrice{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Approval2{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Approval2Date{get;set;}
		#endregion

}
}