//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Mg.Framework;
namespace RepositoryModel
{
    /// <summary>
    /// 实体类Surface。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("Surface")]
    [Serializable]
    public partial class Surface:BaseModel
    {
       #region Model 
		/// <summary>
		/// 
		/// </summary>
		public int RowNo{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SurfaceCode{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SurfaceName{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? SurfaceCategoryID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public byte[] Picture{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ColorPlate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public bool? IsStop{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Mender{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ModifyDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public long AutoID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? CraftID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Text{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string BillType{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string CloseUser{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CloseDate{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ColorPricingClass{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string FactoryColor{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string TheFactoryLogo{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SurfaceTreatmentMaterials{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Remark{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string ManufacturerPowder{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string SurfaceType{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public decimal? SupportTolerance{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? BSurfaceID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public Guid? ASurfaceID{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public string Maker{get;set;}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? MakeDate{get;set;}
		#endregion

}
}