//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Mg.Framework;
namespace RepositoryModel
{
    /// <summary>
    /// 实体类Sys_MenuButton。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("Sys_MenuButton")]
    [Serializable]
    public partial class Sys_MenuButton:BaseModel
    {
       #region Model 
		/// <summary>
		/// 菜单代码
		/// </summary>
		public string MenuCode{get;set;}
		/// <summary>
		/// 按钮代码
		/// </summary>
		public string ButtonCode{get;set;}
		/// <summary>
		/// 按钮排序
		/// </summary>
		public int ButtonSort{get;set;} 
		/// <summary>
		/// 按钮文本
		/// </summary>
		public string ButtonText{get;set;}
		#endregion

}
}