//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Mg.Framework;

namespace RepositoryModel
{
    /// <summary>
    /// 实体类Sys_Menu。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("Sys_Menu")]
    [Serializable]
    public partial class Sys_Menu : BaseModel
    {
        #region Model
        public Guid ParentId { get; set; }
        /// <summary>
        /// 菜单代码
        /// </summary> 
        public string MenuCode { get; set; }
        /// <summary>
        /// 菜单名称
        /// </summary>
        public string MenuName { get; set; }
        /// <summary>
        /// 父级菜单代码
        /// </summary>
        public string ParentCode { get; set; } 
        /// <summary>
        /// 菜单类型：0=未定义 1=目录 2=页面 7=备用1 8=备用2 9=备用3
        /// </summary>
        public int MenuType { get; set; } 
        /// <summary>
        /// 按钮模式：0=未定义 1=动态按钮 2=静态按钮 3=无按钮
        /// </summary>
        public int ButtonMode { get; set; } 
        /// <summary>
        /// 菜单导航URL
        /// </summary>
        public string Url { get; set; }
        /// <summary>
        /// 图标class
        /// </summary>
        public string IconClass { get; set; }
        /// <summary>
        /// 图标Url
        /// </summary>
        public string IconUrl { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 是否启用
        /// </summary>
        public int Enabled { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public string AddBy { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? AddOn { get; set; }
        /// <summary>
        /// 编辑人
        /// </summary>
        public string EditBy { get; set; }
        /// <summary>
        /// 编辑时间
        /// </summary>
        public DateTime? EditOn { get; set; }
        #endregion

    }
}