//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Chloe.Entity;
using Mg.Framework;
namespace RepositoryModel
{
    /// <summary>
    /// 实体类Sys_UserRole。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableAttribute("Sys_UserRole")]
    [Serializable]
    public partial class Sys_UserRole:BaseModel
    {
       #region Model
		/// <summary>
		/// 用户编号
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		public int UserId{get;set;}
		/// <summary>
		/// 角色代码
		/// </summary>
		[ColumnAttribute(IsPrimaryKey = true)]
		public string RoleCode{get;set;}
		#endregion

}
}